export enum AccessType {
  READER = 'reader',
  USER = 'user',
  ADMIN = 'admin',
}

export enum ApiTypes {
  GET = 'GET',
  POST = 'POST',
  PUT = 'PUT',
  DELETE = 'DELETE',
}

export enum API {
  AddLabels = 'api/v1/project/add-labels',
  AddProjects = 'api/v1/project/create',
  AddRun = 'api/v1/run/create',
  AddSquads = 'api/v1/project/add-squads',
  AddTest = 'api/v1/test/create',
  AddTestBulk = 'api/v1/test/bulk-add',
  AddToken = 'api/v1/token/generate',
  UploadAttachment = 'api/v1/run/upload-attachment',
  DeleteAttachment = 'api/v1/run/delete-attachment',
  DeleteBulkTests = 'api/v1/test/bulk-delete',
  DeleteRun = 'api/v1/run/delete',
  DeleteTest = 'api/v1/test/delete',
  DeleteToken = 'api/v1/token/delete',
  DownloadReport = 'api/v1/run/report-download',
  DownloadTests = 'api/v1/tests/download',
  EditProject = 'api/v1/project/edit',
  EditProjectStatus = 'api/v1/project/update-status',
  EditRun = 'api/v1/run/edit',
  EditTest = 'api/v1/test/update',
  EditTestsInBulk = 'api/v1/test/bulk-update',
  GetAutomationStatus = 'api/v1/automation-status',
  GetLabels = 'api/v1/labels',
  GetOrgDetails = 'api/v1/org/detail',
  GetOrgsList = 'api/v1/orgs',
  GetPlatforms = 'api/v1/platform',
  GetPriority = 'api/v1/priority',
  GetProjectDetail = 'api/v1/project/detail',
  GetProjects = 'api/v1/projects',
  GetRuns = 'api/v1/runs',
  GetRunStateDetail = 'api/v1/run/state-detail',
  GetRunTestsList = 'api/v1/run/tests',
  GetRunTestStatus = 'api/v1/run/test-status',
  GetSections = 'api/v1/project/sections',
  GetSquads = `api/v1/project/squads`,
  GetTestCoveredBy = 'api/v1/test-covered-by',
  GetTestDetails = 'api/v1/test/details',
  GetTests = 'api/v1/project/tests',
  GetTestsCount = 'api/v1/project/tests-count',
  GetTestStatusHistory = 'api/v1/test/test-status-history',
  GetTestStatusHistoryInRun = 'api/v1/run/test-status-history',
  GetType = 'api/v1/type',
  GetUserDetails = 'api/v1/user/details',
  RunDetail = 'api/v1/run/detail',
  RunLock = 'api/v1/run/lock',
  RunRemoveTest = 'api/v1/run/remove-tests',
  RunReset = 'api/v1/run/reset',
  RunSaveTestResult = 'api/v1/run/save-test-result',
  RunUpdateTestStatus = 'api/v1/run/update-test-status',
  GetAllUser = 'api/v1/all-users',
  UpdateUserRole = 'api/v1/user/update-role',
  AddSection = 'api/v1/project/add-section',
  EditSection = 'api/v1/project/edit-section',
}

export const API_RESOLUTION_PATHS = {
  [API.AddLabels]: 'routes/api/v1/addLabels.ts',
  [API.AddProjects]: 'routes/api/v1/createProjects.ts',
  [API.AddRun]: 'routes/api/v1/createRun.ts',
  [API.AddSquads]: 'routes/api/v1/addSquads.ts',
  [API.AddTest]: 'routes/api/v1/createTest.ts',
  [API.AddTestBulk]: 'routes/api/v1/bulkAddTest.ts',
  [API.AddToken]: 'routes/api/v1/generateToken.ts',
  [API.UploadAttachment]: 'routes/api/v1/uploadAttachment.ts',
  [API.DeleteAttachment]: 'routes/api/v1/deleteAttachment.ts',
  [API.DeleteBulkTests]: 'routes/api/v1/bulkDeleteTests.ts',
  [API.DeleteRun]: 'routes/api/v1/deleteRun.ts',
  [API.DeleteTest]: 'routes/api/v1/deleteTest.ts',
  [API.DeleteToken]: 'routes/api/v1/deleteToken.ts',
  [API.DownloadReport]: 'routes/api/v1/downloadReport.ts',
  [API.DownloadTests]: 'routes/api/v1/downloadTests.ts',
  [API.EditProject]: 'routes/api/v1/editProject.ts',
  [API.EditProjectStatus]: 'routes/api/v1/updateProjectStatus.ts',
  [API.EditRun]: 'routes/api/v1/editRun.ts',
  [API.EditTest]: 'routes/api/v1/updateTest.ts',
  [API.EditTestsInBulk]: 'routes/api/v1/updateTests.ts',
  [API.GetAutomationStatus]: 'routes/api/v1/automationStatus.ts',
  [API.GetLabels]: 'routes/api/v1/labels.ts',
  [API.GetOrgDetails]: 'routes/api/v1/org.ts',
  [API.GetOrgsList]: 'routes/api/v1/orgList.ts',
  [API.GetPlatforms]: 'routes/api/v1/platform.ts',
  [API.GetPriority]: 'routes/api/v1/priority.ts',
  [API.GetProjectDetail]: 'routes/api/v1/projectData.ts',
  [API.GetProjects]: 'routes/api/v1/projects.ts',
  [API.GetRuns]: 'routes/api/v1/runs.ts',
  [API.GetRunStateDetail]: 'routes/api/v1/runMetaInfo.ts',
  [API.GetRunTestsList]: 'routes/api/v1/runTestsList.ts',
  [API.GetRunTestStatus]: 'routes/api/v1/testStatus.ts',
  [API.GetSections]: 'routes/api/v1/sections.ts',
  [API.GetSquads]: 'routes/api/v1/squads.ts',
  [API.GetTestCoveredBy]: 'routes/api/v1/testCoveredBy.ts',
  [API.GetTestDetails]: 'routes/api/v1/testDetails.ts',
  [API.GetTests]: 'routes/api/v1/tests.ts',
  [API.GetTestsCount]: 'routes/api/v1/testsCount.ts',
  [API.GetTestStatusHistory]: 'routes/api/v1/testStatusHistory.ts',
  [API.GetTestStatusHistoryInRun]: 'routes/api/v1/testStatusHistoryOfRun.ts',
  [API.GetType]: 'routes/api/v1/type.ts',
  [API.GetUserDetails]: 'routes/api/v1/userDetails.ts',
  [API.RunDetail]: 'routes/api/v1/runData.ts',
  [API.RunLock]: 'routes/api/v1/lockRun.ts',
  [API.RunRemoveTest]: 'routes/api/v1/removeTestFromRun.ts',
  [API.RunReset]: 'routes/api/v1/markPassedAsRetest.ts',
  [API.RunSaveTestResult]: 'routes/api/v1/saveTestResult.ts',
  [API.RunUpdateTestStatus]: 'routes/api/v1/updateStatusTestRuns.ts',
  [API.GetAllUser]: 'routes/api/v1/getAllUser.ts',
  [API.UpdateUserRole]: 'routes/api/v1/updateUserType.ts',
  [API.AddSection]: 'routes/api/v1/addSection.ts',
  [API.EditSection]: 'routes/api/v1/editSection.ts',
}

export const CLOSED_API = {
  // GenerateToken: 'api/v1/generateToken',
}

export const ApiToTypeMap: {
  [key in API]: ApiTypes
} = {
  [API.AddLabels]: ApiTypes.POST,
  [API.AddProjects]: ApiTypes.POST,
  [API.AddRun]: ApiTypes.POST,
  [API.AddSquads]: ApiTypes.POST,
  [API.AddTest]: ApiTypes.POST,
  [API.AddTestBulk]: ApiTypes.POST,
  [API.AddToken]: ApiTypes.POST,
  [API.UploadAttachment]: ApiTypes.POST,
  [API.DeleteAttachment]: ApiTypes.DELETE,
  [API.DeleteBulkTests]: ApiTypes.DELETE,
  [API.DeleteRun]: ApiTypes.DELETE,
  [API.DeleteTest]: ApiTypes.DELETE,
  [API.DeleteToken]: ApiTypes.DELETE,
  [API.DownloadReport]: ApiTypes.GET,
  [API.DownloadTests]: ApiTypes.GET,
  [API.EditProject]: ApiTypes.PUT,
  [API.EditProjectStatus]: ApiTypes.PUT,
  [API.EditRun]: ApiTypes.PUT,
  [API.EditTest]: ApiTypes.PUT,
  [API.EditTestsInBulk]: ApiTypes.PUT,
  [API.GetAutomationStatus]: ApiTypes.GET,
  [API.GetLabels]: ApiTypes.GET,
  [API.GetOrgDetails]: ApiTypes.GET,
  [API.GetOrgsList]: ApiTypes.GET,
  [API.GetPlatforms]: ApiTypes.GET,
  [API.GetPriority]: ApiTypes.GET,
  [API.GetProjectDetail]: ApiTypes.GET,
  [API.GetProjects]: ApiTypes.GET,
  [API.GetRuns]: ApiTypes.GET,
  [API.GetRunStateDetail]: ApiTypes.GET,
  [API.GetRunTestsList]: ApiTypes.GET,
  [API.GetRunTestStatus]: ApiTypes.GET,
  [API.GetSections]: ApiTypes.GET,
  [API.GetSquads]: ApiTypes.GET,
  [API.GetTestCoveredBy]: ApiTypes.GET,
  [API.GetTestDetails]: ApiTypes.GET,
  [API.GetTests]: ApiTypes.GET,
  [API.GetTestsCount]: ApiTypes.GET,
  [API.GetTestStatusHistory]: ApiTypes.GET,
  [API.GetTestStatusHistoryInRun]: ApiTypes.GET,
  [API.GetType]: ApiTypes.GET,
  [API.GetUserDetails]: ApiTypes.GET,
  [API.RunDetail]: ApiTypes.GET,
  [API.RunLock]: ApiTypes.PUT,
  [API.RunRemoveTest]: ApiTypes.PUT,
  [API.RunReset]: ApiTypes.PUT,
  [API.RunSaveTestResult]: ApiTypes.PUT,
  [API.RunUpdateTestStatus]: ApiTypes.PUT,
  [API.GetAllUser]: ApiTypes.GET,
  [API.UpdateUserRole]: ApiTypes.PUT,
  [API.AddSection]: ApiTypes.POST,
  [API.EditSection]: ApiTypes.PUT,
}
